#pragma once

#define BUFFER_SIZE 100
#define PRODUCERS_COUNT 5
#define CONSUMERS_COUNT 5
#define WORK_TIME_MS 100
#define PRODUCERS_CONDITION_VAR_AWAITING_NS 5
#define CONSUMERS_CONDITION_VAR_AWAITING_NS 5